apiVersion: apps/v1
kind: Deployment
metadata:
  name: student0-deployment
  namespace: student0
spec:
  selector:
    matchLabels:
      app: student0
  template:
    metadata:
      labels:
        app: student0
    spec:
      containers:
      - name: student0
        image: registry.tanzu.dk/ops2devops/student0:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student0
spec:
  type: NodePort
  selector:
    app: student0
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010 # Remember to change to student number.

